-- MySQL Script generated by MySQL Workbench
-- Wed Jul 17 21:21:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_winback
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_winback
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_winback` DEFAULT CHARACTER SET utf8 ;
USE `db_winback` ;

-- -----------------------------------------------------
-- Table `db_winback`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_winback`.`CLIENTE` (
  `idCLIENTE` INT NOT NULL,
  `TIPO_CLIENTE` VARCHAR(45) NULL,
  `NOMBRE_CLIENTE` VARCHAR(45) NULL,
  `TIPO_DOC` VARCHAR(45) NULL,
  `NRO_DOC` INT NULL,
  `DISTRITO` VARCHAR(45) NULL,
  `PROVINCIA` VARCHAR(45) NULL,
  `DEPARTAMENTO` VARCHAR(45) NULL,
  PRIMARY KEY (`idCLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_winback`.`CAMPAÑA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_winback`.`CAMPAÑA` (
  `idCAMPAÑA` INT NOT NULL,
  `NOMBRE_CAMPAÑA` VARCHAR(45) NULL,
  PRIMARY KEY (`idCAMPAÑA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_winback`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_winback`.`PRODUCTO` (
  `idPRODUCTO` INT NOT NULL,
  `TIPO_PRODUCTO` VARCHAR(45) NULL,
  `SUB_PRODUCTO` VARCHAR(45) NULL,
  `TECNOLOGIA_INTERNET` VARCHAR(45) NULL,
  `CAMPAÑA_idCAMPAÑA` INT NOT NULL,
  PRIMARY KEY (`idPRODUCTO`),
  INDEX `fk_PRODUCTO_CAMPAÑA1_idx` (`CAMPAÑA_idCAMPAÑA` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_CAMPAÑA1`
    FOREIGN KEY (`CAMPAÑA_idCAMPAÑA`)
    REFERENCES `db_winback`.`CAMPAÑA` (`idCAMPAÑA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_winback`.`CONTRATO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_winback`.`CONTRATO` (
  `idCLIENTE` INT NOT NULL,
  `idCAMPAÑA` INT NOT NULL,
  `idPRODUCTO` INT NOT NULL,
  `fecVENTA` DATE NOT NULL,
  `fecALTA` DATE NULL,
  `CLIENTE_idCLIENTE` INT NOT NULL,
  PRIMARY KEY (`idCLIENTE`, `idPRODUCTO`, `idCAMPAÑA`),
  INDEX `fk_CONTRATO_CLIENTE_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_CONTRATO_CLIENTE`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `db_winback`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_winback`.`PRODUCTO_DETALLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_winback`.`PRODUCTO_DETALLE` (
  `idCAMPAÑA` INT NOT NULL,
  `idPRODUCTO` INT NOT NULL,
  `CONTRATO_idCLIENTE` INT NOT NULL,
  `CONTRATO_idPRODUCTO` INT NOT NULL,
  `CONTRATO_idCAMPAÑA` INT NOT NULL,
  `CAMPAÑA_idCAMPAÑA` INT NOT NULL,
  PRIMARY KEY (`idCAMPAÑA`, `idPRODUCTO`),
  INDEX `fk_PRODUCTO_DETALLE_CONTRATO1_idx` (`CONTRATO_idCLIENTE` ASC, `CONTRATO_idPRODUCTO` ASC, `CONTRATO_idCAMPAÑA` ASC) VISIBLE,
  INDEX `fk_PRODUCTO_DETALLE_CAMPAÑA1_idx` (`CAMPAÑA_idCAMPAÑA` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_DETALLE_CONTRATO1`
    FOREIGN KEY (`CONTRATO_idCLIENTE` , `CONTRATO_idPRODUCTO` , `CONTRATO_idCAMPAÑA`)
    REFERENCES `db_winback`.`CONTRATO` (`idCLIENTE` , `idPRODUCTO` , `idCAMPAÑA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_DETALLE_CAMPAÑA1`
    FOREIGN KEY (`CAMPAÑA_idCAMPAÑA`)
    REFERENCES `db_winback`.`CAMPAÑA` (`idCAMPAÑA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
